### ISSUE TITLE
Teensy 3.2 Shortatge

### ISSUE THREAD

**Issue by arquecc** [kgerrits/Emcoturn_toolchanger#1]
Hi there,

I'm facing an issue with the Teensy 3.2 as it appears that it will no longer be available and the manufacturer recommends using the Teensy 4.0 instead. I'm wondering if it's possible to modify the PCB to adapt to the Teensy 4.0. Could you please advise on this matter?

Thank you!

**Comment by kgerrits** [comment]
Hi,

I think this should be not too much work. I will look into this coming week.

**Comment by arquecc** [comment]
Hi,

Many thanks.
I'll wait for the update and thanks again for your support.
